const userData = {
  githubUsername: 'thutasann',
  name: 'THUTA SANN',
  designation: 'PASSIONATE CODER',
  email: 'thutasann2002@gmail.com',
  phone: '+95 9895388882',
  address: 'S/Okkalpa, Yangon, Myanmar',
  projects: [
    {
      id: 1,
      category: 'WEB3.0',
      title: 'Coinbase Blockchain app',
      link: 'https://coinbase-tts.vercel.app/',
      imgUrl: '/coinbase.png',
    },
    {
      id: 2,
      category: 'WEB3.0',
      title: 'Uniswap Blockchain app',
      link: 'https://uniswap-thuta-thutasan.vercel.app/',
      imgUrl: '/uniswap.png',
    },
    {
      id: 3,
      category: 'React.js',
      title: 'Edubase Idea Sharing app',
      link: 'http://edubase-d4c34.web.app/',
      imgUrl: '/edubase.png',
    },
    {
      id: 4,
      category: 'React.js',
      title: 'Ex Portfolio site',
      link: 'https://thutasann.herokuapp.com/',
      imgUrl: '/oldportfolio.png',
    },
    {
      id: 5,
      category: 'Next.js',
      title: 'Current Portfolio site',
      link: 'https://thutasann.vercel.app/',
      imgUrl: '/thutasann.png',
    },
    {
      id: 6,
      category: 'React.js',
      title: 'Slack Clone',
      link: 'https://slack-a3bcd.web.app/',
      imgUrl: '/slackclone.png',
    },
    {
      id: 7,
      category: 'React.js',
      title: 'Gmail Clone',
      link: 'https://clone-e131e.web.app/',
      imgUrl: '/gmailclone.png',
    },
    {
      id: 8,
      category: 'Next.js',
      title: 'Twitter Clone',
      link: 'https://twitter-clone-thutasann.vercel.app/',
      imgUrl: '/twitterclone.png',
    },
    {
      id: 9,
      category: 'React.js',
      title: 'LinkedIn Clone',
      link: 'https://linkedin-3ea13.web.app/',
      imgUrl: '/linkedinclone.png',
    },
    {
      id: 10,
      category: 'React Native',
      title: 'React Native Signal Clone',
      link: 'https://signal-clone-b6a27.web.app/',
      imgUrl: '/rnclone.png',
    },
    {
      id: 11,
      category: 'Next.js',
      title: 'NEXTJS Reddit Clone',
      link: 'https://reddit-thuta.vercel.app/',
      imgUrl: '/redditclone.png',
    },
    {
      id: 12,
      category: 'Angular',
      title: 'Angular GameDB App',
      link: 'https://videogame-tts.vercel.app/',
      imgUrl: '/gamedbclone.png',
    },
    {
      id: 13,
      category: 'Angular',
      title: 'Angular Currency Checker',
      link: 'https://currencychecker-thuta.vercel.app/',
      imgUrl: '/angular-currency.png',
    },
    // {
    //   id: 14,
    //   category: 'React.js',
    //   title: "Hsu Ye Ywel Portfolio",
    //   link: "https://hsuyeywel-6f42d.web.app/",
    //   imgUrl: "/hsu1.png"
    // },
    {
      id: 16,
      category: 'Next.js',
      title: 'Goblin Gangs',
      link: 'https://goblingangs.vercel.app/',
      imgUrl: '/goblingangs.png',
    },
    {
      id: 16,
      category: 'Next.js',
      title: 'Framer Motion Portfolio',
      link: 'https://hsuyeywel.vercel.app/',
      imgUrl: '/hsu-framer-motion.png',
    },
    {
      id: 16,
      category: 'Next.js',
      title: 'Apple Plus Clone Landing Page',
      link: 'https://apple-plus-clone-thuta.vercel.app/',
      imgUrl: '/apple-plus-clone.png',
    },
    {
      id: 17,
      category: 'ChakraUI',
      title: 'Chakra ECommerce',
      link: 'https://chakra-tecom.vercel.app/',
      imgUrl: '/chakra-ecom.png',
    },
    {
      id: 19,
      category: 'UIKit',
      title: 'Netflix Clone',
      link: 'https://www.linkedin.com/feed/update/urn:li:activity:6997520383801270272/',
      imgUrl: '/netflix-clone.png',
    },
    {
      id: 20,
      category: 'SwiftUI',
      title: 'SwiftUI KickOff',
      link: 'https://github.com/thutasann/SwiftUI-Kick-Off#readme',
      imgUrl: '/swiftui-kickoff.png',
    },
    {
      id: 20,
      category: 'SwiftUI',
      title: 'UBER UI',
      link: 'https://github.com/thutasann/swiftui-UBER-rebuild#readme',
      imgUrl: '/swift-ui-uber.png',
    },
    {
      id: 20,
      category: 'SwiftUI',
      title: 'Animated Weather App UI',
      link: 'https://github.com/thutasann/swiftui-weather-app#readme',
      imgUrl: '/swift-ui-weather-app.png',
    },
    {
      id: 20,
      category: 'SwiftUI',
      title: 'Core Data TaskManager',
      link: 'https://github.com/thutasann/swiftui-coredata-task-manager#readme',
      imgUrl: '/swiftui-taskmanager.png',
    },
  ],
  about: {
    metaTitle: 'Thuta Sann | Frontend Dev',
    title:
      "I'm a developer that loves building NEXTJS, ANGULAR & SpringBoot and IOS Mobile apps. Also loves building UI/UX with TailwindCSS, Material UI, ChakraUI, etc",
    description: [
      `I've been developing websites since I was 18 years old. I started my web development career with HTML, CSS and PHP. and After PHP, I've learnt Laravel web Framework.`,
      `After learning HTML and struggling with CSS, I came up with a brilliant idea of using Bootstrap and Tailwind so that I don't have to style everything by myself and - for obvious reasons - if you knew Tailwind, you were cool. 👽`,
      `But now, I've been coding in React.js, React Native, Nextjs, Nestjs, MongoDB, MySQL, Tailwind, Flutter programming languages etc to name a few. Although I barely know the syntax (Psst, Stack overflow!), I consider myself a Ninja developer I'm laughing right now.
      Now, I am currently exploring Flutter Programming Language as a Mobile Development & Spring Boot Framework as a Backend Development for Microservices meanwhile Exploring deeply to NextJs.`,
    ],
    keywords: ['Thuta Sann', 'thutadev', 'Thuta Dev', 'Thutasann Developer'],
    currentProject: 'UIKit Netflix Clone',
    currentProjectUrl: 'https://www.linkedin.com/feed/update/urn:li:activity:6997520383801270272/',
  },
  experience: [
    {
      title: 'Frontend Developer',
      company: 'Codigo Mobile & Web App Development Company',
      year: '2022 - Present',
      companyLink: 'https://www.codigo.co/',
      desc: 'Frontend Developer who is responsible for Website Development and PWA Development with ReactJS and NextJS',
    },
    {
      title: 'Global High Achiever Award',
      company: 'NCC Education',
      year: '2022',
      companyLink: 'https://www.nccedu.com/',
      desc: "I'm glad to announce that I am awarded the Global High Achiever Award From the NCC Education (UK).",
    },
    {
      title: 'Junior Developer',
      company: 'Yoma Bank Ltd',
      year: '2022',
      companyLink: 'https://yomabank.com/',
      desc: 'Web Developer who is responsible for building web application with Angular and Spring boot',
    },
    {
      title: 'Frontend Developer',
      company: 'Digital Laboratory',
      year: '2022',
      companyLink: 'https://digitallaboratory.net/',
      desc: 'Frontend Developer who is responsible for building website with Gatsby.js, Nextjs, WordPress, Strapi',
    },
    {
      title: 'Graduation',
      company: 'University of Greenwich',
      year: '2022',
      companyLink: 'https://www.gre.ac.uk/',
      desc: 'Qualified BSc (Hons) in Computing from University of Greenwich',
    },
    {
      title: 'Freelance Web Developer',
      company: 'Self-employed',
      year: '2021',
      companyLink: 'https://thutasann.herokuapp.com/',
      desc: 'Developed ReactJS websites as a Freelance developer',
    },
    {
      title: 'Level 5 Diploma in Computing',
      company: 'NCC Education',
      year: '2020',
      companyLink: 'https://www.nccedu.com/',
      desc: 'Qualified Level 5 Diploma in Computing from NCC Education',
    },
    {
      title: 'Level 4 Diploma in Computing',
      company: 'NCC Education',
      year: '2019',
      companyLink: 'https://www.nccedu.com/',
      desc: 'Qualified Level 4 Diploma in Computing from NCC Education',
    },
    {
      title: 'Matriculation',
      company: 'No(1) B.E.H.S Thingangyun',
      year: '2018',
      companyLink: '#',
      desc: 'Matriculated with Flying colors',
    },
  ],
  resumeUrl: 'https://drive.google.com/file/d/11CVNmYzbdW2OCROig8gHbPJvThP9mMZB/view?usp=sharing',
  socialLinks: {
    instagram: 'https://www.instagram.com/thuta_sann/',
    twitter: 'https://twitter.com/Thutasann3',
    linkedin: 'https://www.linkedin.com/in/thuta-sann-3508a7199/',
    github: 'http://github.com/thutasann/',
    facebook: 'https://www.facebook.com/thuta.sann.52',
  },
}

export const SkillsData: ISkill[] = [
  {
    name: 'Web',
    x: '',
    y: '',
    isWeb: true,
  },
  {
    name: 'ReactJs',
    x: '-20vw',
    y: '6vw',
  },
  {
    name: 'GatsbyJS',
    x: '-20vw',
    y: '-2vw',
  },
  {
    name: 'NextJS',
    x: '-15vw',
    y: '-10vw',
  },
  {
    name: 'TailWindCSS',
    x: '20vw',
    y: '6vw',
  },
  {
    name: 'Typescript',
    x: '0vw',
    y: '-10vw',
  },
  {
    name: 'NodeJS',
    x: '0vw',
    y: '-20vw',
  },
  {
    name: 'MongoDB',
    x: '15vw',
    y: '-10vw',
  },

  {
    name: 'Firebase',
    x: '20vw',
    y: '-3vw',
  },

  {
    name: 'Git',
    x: '0vw',
    y: '12vw',
  },
]

export default userData
